### PR TITLE
Fix installation, icon and desktop file

### LINKED ISSUE #308: pure CMake build: "make install" won't install shared files
I've built wcm with cmake and did `sudo make install`. `/usr/share/wcm/...` files were not installed. Moreover, they should go to `/usr/local/share/`. After copying them to `/usr/local/share/`by hand, they still were not picked up (wcm looked in `/usr/share/` instead).

### PR DESCRIPTION
**Pull request by AMDmi3**
Fixes #308

### CODE REVIEW

**Comment by corporateshark** [comment]
What about ``make install``?

**Comment by AMDmi3** [comment]
> What about ```make install```?

What's about it?

**Comment by corporateshark** [comment]
@AMDmi3 just asking. Merged.

**Comment by AMDmi3** [comment]
I don't understand the question. This fixes make install with cmake, and shouldn't affect legacy makefile (however it'd be better to recheck).

**Comment by corporateshark** [comment]
I don't have Linux here, that's why I was asking.

**Pull request merged**
