### PR TITLE
File attributes (Windows-only right now)

### PR DESCRIPTION
**Pull request by corporateshark**

### CODE REVIEW

**Comment by helgp** [comment]
Far has menu item: "F9-&Files-File &attributes"

**Comment by corporateshark** [comment]
91740e520441ef670b3acac9bddf0ad79492cff

**Comment by helgp** [comment]
While still in context, Far also has F9-&Files-A&pply command" Ctrl-G menu item. Ctrl-G works in wcm - may be to add it too?

In general, it might be good idea to "document" new wcm shortcuts as menu items wherever applicable.

**Comment by corporateshark** [comment]
0aa143a924ce8a8f13a98f752011387a2cc80aab

**Pull request merged**
