### PR TITLE
Temporary panel. Mod1 #213

### PR DESCRIPTION
**Pull request by helgp**
How to use:
Access temporary panel via Alt-F1|F2 - "temporary (alpha test)".

- View-Edit-Delete-[shift]Copy/Move operations on files work on the temp panel.
- On Windows all temporary items should be at the same drive (like C:)
- Neither works on directories (yet) - red dialog instead
- Neither works on non-local FS (should it?) - red dialog instead

### CODE REVIEW

**Comment by corporateshark** [comment]
Looks like a nice major feature!
How stable is it?

**Comment by helgp** [comment]
I stated in the commit message that functionality is limited. 

The existing functionality does not break the wcm, and managed file systems - at least in my Win|Linux environments.

**Comment by corporateshark** [comment]
Let's try it then.

**Comment by corporateshark** [comment]
Works on OS X. However, having directories there would be nice (same as in Far).

**Pull request merged**
