### PR TITLE
Fixed #390

### LINKED ISSUE #390: F3 on ".." should show size of the selected files/folders
Do:

- select some files in a folder
- move cursor to ..
- press F3

Observe:

- no size information is shown

Should be:

- show combined size of the selected items

### PR DESCRIPTION
**Pull request by helgp**

### CODE REVIEW

**Comment by corporateshark** [comment]
Works for selected folders, but not for selected files.

**Comment by helgp** [comment]
What is your test case?
Mine is:
- Select some files
- Place cursor to ..
- Press F3
This works.

**Comment by corporateshark** [comment]
bug_390

**Comment by corporateshark** [comment]
Exactly as you say, but does not work.

**Comment by helgp** [comment]
Head branch of corporateshark/WalCommander reveals the bug, exactly like you stated. Head of helgp/WalCommander does not - neither on Windows, nor on Linux. Please use "rebuild all", and double check that you use correct source stream for the test: the line 191 in dircalc.cpp should be "else", like it is in my stream.

I have no other ideas.

**Pull request merged**
