### PR TITLE
#319 - Linux fonts: antialiasing for TTF in dialogs/menus; usermenu font size fixed

### PR DESCRIPTION
**Pull request by singalen**
What I wished in #319.

### CODE REVIEW

**Comment by corporateshark** [comment]
Will it break this thing again?
http://forum.ubuntu.ru/index.php?topic=149195.msg2025001#msg2025001

**Comment by singalen** [comment]
Um, it does. I have 3d switched off, so didn't notice. Will fix eventually, give me sime time.

**Comment by corporateshark** [comment]
FreeType output can be used as an alpha-transparency value to blend the text with the background. Would be actually better to use the single setting for text rendering mode everywhere. A caching mechanism would be required. Will do the caching later, once other more vital things are there, after 0.19.1.

**Comment by singalen** [comment]
`wal` claims blending is much slower. Maybe this optimization won't be premature?..

**Comment by corporateshark** [comment]
I think it can be added as an option.

**Comment by singalen** [comment]
Wait, this change actually didn't break the panels. `TextOutF()` is already there and stays there.
Linux panels with 3d look are actually broken, though, but it's much better then the ugly non-antialiased look.

**Comment by singalen** [comment]
Related issue: #429

**Pull request merged**
