### PR TITLE
Temporary panel #213. Mod4.

### PR DESCRIPTION
**Pull request by helgp**
- Added: Alt-F7 search results can now be placed to temporary panel (with "Panel" button on Alt-F7 search results output)
- Added: Alt-F7 search can now be performed within files in temporary panel. Results of the search within temp panel can be panelized to another temp panel
- Fixed: Copying file/folder between two temp panels of the same base works now

### CODE REVIEW

**Comment by corporateshark** [comment]
Why cannot we mix files from different file systems?

**Comment by helgp** [comment]
- Easier to implement. FS'es are heavy clPtr-controlled objects in wcm. Very few instances of the FS are created now. The FS objects are not exposed to application scope. I was afraid to embed the FS to every item in temp list. Think of the use case: Ctrl-L (FS stat), and move cursor across items in temp panel. The stat panel has to be updated on each cursor movement. 
- Better visual presentation in panels. The items like
sftp://myusername@mywebsite.com:22/home/myusername/walcommander/src/panel.cpp  
will be cut on panel screens. 
- Personally, I never ever used temporary panel in Far to store files across volumes. 

It can be added if a reasonable use case will be presented.

**Comment by corporateshark** [comment]
FS is quite lightweight, indeed, so this cannot be a valid reason. Btw, having ~1M of clPtr-controlled objects is not a problem.

**Comment by helgp** [comment]
FS is polymorphic. Look, e.g. at FSSftp class. It has 5 member classes embedded, and 3 pointers to volatile objects with unclear management scope. 1M copies of that monster, which are called all the way from core code, are hard to watch carefully in further development. I am not even sure that copying Mutex object, which is present in two instances among the 5 members, does not break FSSftp communication over a shared TCP socket.

Also, FSArchive is in my list. It is going add other monsters.

**Comment by corporateshark** [comment]
Yes, it is polyporphic. However, you can store smart-pointers to it elsewhere.

Archives: https://github.com/corporateshark/WalCommander/issues/26

**Pull request merged**
